### ISSUE TITLE
Failed to build on Mac OSX 10.12 with Python 3.5.2

### ISSUE THREAD

**Issue by t20100** [silx-kit/pyFAI#470]
Running `python setup.py build --no-openmp` on OSX from a fresh clone failed with:

```
...
pyFAI/ext/histogram.c:242:10: fatal error: 'omp.h' file not found
#include "omp.h"
         ^
1 warning and 1 error generated.
In file included from pyFAI/ext/histogram.c:239:
In file included from /Users/tvincent/venv/py3env/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/tvincent/venv/py3env/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /Users/tvincent/venv/py3env/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:
/Users/tvincent/venv/py3env/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
pyFAI/ext/histogram.c:242:10: fatal error: 'omp.h' file not found
#include "omp.h"
         ^
1 warning and 1 error generated.
error: Command "/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -IpyFAI/ext/include -IpyFAI/ext -I/Users/tvincent/venv/py3env/lib/python3.5/site-packages/numpy/core/include -I/Users/tvincent/venv/py3env/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c pyFAI/ext/histogram.c -o build/temp.macosx-10.6-intel-3.5/pyFAI/ext/histogram.o" failed with exit status 1
```

touch on pyFAI/ext/histogram.pyx fixed the issue.
Any way to force cythonize (especially when not using openmp), or to store cythonize files without openmp?

**Comment by kif** [comment]
indeed one needs to "touch pyFAI/ext/*.pyx" 
we could enforce cythonize on OSX. Anyway Cython is already a build dependency on OSX, it would not be an additional dependency. This is simply  a modification on the setup.py

**Comment by vallsv** [comment]
I do some improvment https://github.com/silx-kit/pyFAI/pull/472

**Comment by kif** [comment]
related to #475

**Comment by kif** [comment]
actually the issue is closed
