### ISSUE TITLE
New 1D integrator doesn't work in 0.19

### ISSUE THREAD

**Issue by jbhopkins** [silx-kit/pyFAI#1331]
I'm using pyFAI 0.19 on MacOS 10.14.6 (edit: python 3.7.4, installed using pip). I'm running some test code on the variance based off the jupyter notebook that you created (code is below). When I try to use the new integrator (_integrate1d_ng) with the nosplit_csr method it gives the following error:

```python
Traceback (most recent call last):
  File "test_pyfai.py", line 364, in <module>
    ai_new_c2, ai_new_nbins = calc_distribution(ai, kwarg, integrator='new')
  File "test_pyfai.py", line 299, in calc_distribution
    r = integrate(data, variance=data, **kwarg)
  File "/Users/jessehopkins/miniconda2/envs/py3/lib/python3.7/site-packages/pyFAI/azimuthalIntegrator.py", line 1641, in _integrate1d_ng
    normalization_factor=normalization_factor)
  File "pyFAI/ext/splitBBoxCSR.pyx", line 721, in pyFAI.ext.splitBBoxCSR.HistoBBox1d.integrate_ng
AttributeError: 'HistoBBox1d' object has no attribute 'cmask'
```

Full code that I'm using is below:
```python
# Testing chi_squared of the integrators, as per pyFAI notebook online
from scipy.stats import chi2 as chi2_dist
from matplotlib.colors import LogNorm
from pyFAI.detectors import Detector
from pyFAI.azimuthalIntegrator import AzimuthalIntegrator
from pyFAI.method_registry import IntegrationMethod
import time

def chi2_curves(res1, res2):
    """Calculate the Chi2 value for a pair of integrated data"""
    I = res1.intensity
    J = res2.intensity
    l = len(I)
    assert len(J) == l
    sigma_I = res1.sigma
    sigma_J = res2.sigma
    return ((I-J)**2/(sigma_I**2+sigma_J**2)).sum()/(l-1)

def calc_distribution(ai, kwargs, nbins=100, integrator='new'):
    ai.reset()
    results = []
    c2 = []
    if integrator == 'old':
        integrate = ai._integrate1d_legacy
    elif integrator == 'new':
        integrate = ai._integrate1d_ng
    elif integrator == 'default':
        integrate = ai.integrate1d
    for i in range(nimg):
        data = dataset[i, :, :]
        r = integrate(data, variance=data, **kwarg)
        results.append(r)
        for j in range(i):
            c2.append(chi2_curves(r, results[j]))
    c2 = np.array(c2)

    return c2, nbins

pix = 100e-6
shape = (1024, 1024)
npt = 1000
nimg = 1000
wl = 1e-10
I0 = 1e4
Rg = 1.
kwarg = {"npt":npt,
         "correctSolidAngle":False,
         "polarization_factor":None,
         "safe":False}

detector = Detector(pix, pix)
detector.shape = detector.max_shape = shape

ai_init = {"dist":1.0,
           "poni1":0.0,
           "poni2":0.0,
           "rot1":0.0,
           "rot2":0.0,
           "rot3":0.0,
           "detector":detector,
           "wavelength":wl}

ai = AzimuthalIntegrator(**ai_init)

kwarg["method"] = IntegrationMethod.select_one_available("nosplit_csr", 1)

# flat = np.ones(detector.shape)
# res_flat = ai.integrate1d(flat, **kwarg)

# q = np.linspace(0, res_flat.radial.max(), npt)
# I = I0/(1+q**2)
# img_theo = ai.calcfrom1d(q, I, dim1_unit="q_nm^-1", correctSolidAngle=False,
#     polarization_factor=None)

# plt.imshow(img_theo)
# plt.show()

# dataset = np.random.poisson(img_theo, (nimg,) + img_theo.shape)
# np.save('test_chi_data.npy', dataset)

dataset = np.load('test_chi_data.npy')

kwarg = {"npt":npt,
         "method": IntegrationMethod.select_one_available("nosplit_csr", dim=1),
         "correctSolidAngle":True,
         'normalization_factor':10.,
         "safe":False}

#As we use "safe"=False, we need to reset the integrator manually:
ai.reset()
# Azimuthal integrator, correcting solid angle
ai_old_c2, ai_old_nbins = calc_distribution(ai, kwarg, integrator='old')

ai.reset()
# Azimuthal integrator, correcting solid angle
ai_new_c2, ai_new_nbins = calc_distribution(ai, kwarg, integrator='new')

ai.reset()
# Azimuthal integrator, correcting solid angle
ai_default_c2, ai_default_nbins = calc_distribution(ai, kwarg, integrator='default')

# Expected distribution


plt.subplot(3, 1, 1)
h,b,_ = plt.hist(ai_old_c2, ai_old_nbins, label="Measured distibution, old")
y_sim = chi2_dist.pdf(b*(nimg-1), nimg)
y_sim *= h.sum()/y_sim.sum()
plt.plot(b, y_sim, label=r"Chi^2 distribution")

plt.subplot(3, 1, 2)
h,b,_ = plt.hist(ai_new_c2, ai_new_nbins, label="Measured distibution, new")
y_sim = chi2_dist.pdf(b*(nimg-1), nimg)
y_sim *= h.sum()/y_sim.sum()
plt.plot(b, y_sim, label=r"Chi^2 distribution")

plt.subplot(3, 1, 3)
h,b,_ = plt.hist(ai_default_c2, ai_default_nbins, label="Measured distibution, default")
y_sim = chi2_dist.pdf(b*(nimg-1), nimg)
y_sim *= h.sum()/y_sim.sum()
plt.plot(b, y_sim, label=r"Chi^2 distribution")
plt.legend()
plt.show()
```

**Comment by kif** [comment]
Hi Jesse, 
I managed to reproduce the bug. Thanks for reporting it.
